# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fiK1mrdqH_z8VKc8-yFxpGEKl_f7XlZR
"""
import streamlit as st
from PIL import Image
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, Sequential
import zipfile
import os
import tempfile
import glob

# -----------------------------
# Settings
# -----------------------------
IMG_WIDTH, IMG_HEIGHT = 256, 256
VALIDATION_SPLIT = 0.2
SEED = 123
BATCH_SIZE = 32

# Folder to store trained model weights
MODEL_DIR = "models"
os.makedirs(MODEL_DIR, exist_ok=True)

# Classes
freshness_classes = ["fresh", "rotten"]
fruit_classes = ["apple", "banana", "strawberry"]

# -----------------------------
# Data augmentation
# -----------------------------
data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal_and_vertical"),
    layers.RandomRotation(0.2),
    layers.RandomZoom(0.2)
], name="data_augmentation")

# -----------------------------
# Create CNN model
# -----------------------------
def create_cnn_model(num_classes, img_size=(IMG_WIDTH, IMG_HEIGHT, 3), dropout_rate=0.4):
    model = Sequential([
        layers.Input(shape=img_size),
        data_augmentation,
        layers.Rescaling(1./255),

        layers.Conv2D(32, 3, padding='same', activation='relu'),
        layers.MaxPooling2D(2),
        layers.Conv2D(64, 3, padding='same', activation='relu'),
        layers.MaxPooling2D(2),
        layers.Conv2D(128, 3, padding='same', activation='relu'),
        layers.MaxPooling2D(2),
        layers.Dropout(dropout_rate),
        layers.GlobalAveragePooling2D(),

        layers.Dense(64, activation='relu'),
        layers.Dense(num_classes, activation='softmax')
    ])
    return model

# -----------------------------
# Create datasets from folder
# -----------------------------
def create_datasets(data_dir):
    train_ds = tf.keras.utils.image_dataset_from_directory(
        data_dir,
        validation_split=VALIDATION_SPLIT,
        subset="training",
        seed=SEED,
        image_size=(IMG_WIDTH, IMG_HEIGHT),
        batch_size=BATCH_SIZE,
        label_mode='categorical'
    )
    val_ds = tf.keras.utils.image_dataset_from_directory(
        data_dir,
        validation_split=VALIDATION_SPLIT,
        subset="validation",
        seed=SEED,
        image_size=(IMG_WIDTH, IMG_HEIGHT),
        batch_size=BATCH_SIZE,
        label_mode='categorical'
    )
    class_names = train_ds.class_names
    num_classes = len(class_names)

    train_ds = train_ds.cache().shuffle(1000).prefetch(tf.data.AUTOTUNE)
    val_ds = val_ds.cache().prefetch(tf.data.AUTOTUNE)

    return train_ds, val_ds, class_names, num_classes

# -----------------------------
# List saved model weights
# -----------------------------
def get_saved_models():
    return [os.path.basename(f) for f in glob.glob(os.path.join(MODEL_DIR, "*.keras"))]

# -----------------------------
# Streamlit UI
# -----------------------------
st.title("Fruit Freshness & Type Classifier 🍎🍌🍓")
tab = st.tabs(["Train Model", "Inference: Freshness", "Inference: Fruit Type"])

# -----------------------------
# TRAIN MODEL
# -----------------------------
with tab[0]:
    st.header("Train or Check Your Model")
    uploaded_zip = st.file_uploader("Upload dataset ZIP for training", type=["zip"], key="train_zip")
    epochs = st.slider("Epochs", 1, 50, 5, key="train_epochs")
    batch_size = st.select_slider("Batch size", [16, 32, 64], value=32, key="train_batch")

    if uploaded_zip is not None:
        with tempfile.TemporaryDirectory() as tmpdir:
            zip_path = os.path.join(tmpdir, "dataset.zip")
            with open(zip_path, "wb") as f:
                f.write(uploaded_zip.getvalue())
            with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                zip_ref.extractall(tmpdir)
            
            data_dir = tmpdir
            st.write("Dataset ready. Creating dataset...")
            train_ds, val_ds, class_names, num_classes = create_datasets(data_dir)
            
            st.write(f"Detected classes: {class_names}")
            model = create_cnn_model(num_classes=num_classes)
            model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
            
            model_name = st.text_input("Enter a name for the trained model", "my_model", key="train_model_name")
            if st.button("Start Training", key="train_button"):
                st.write("Training started...")
                history = model.fit(train_ds, validation_data=val_ds, epochs=epochs)
                st.success("Training finished!")
                save_path = os.path.join(MODEL_DIR, f"{model_name}.keras")
                model.save_weights(save_path)
                st.write(f"Model weights saved as {save_path}")

# -----------------------------
# INFERENCE: FRESHNESS
# -----------------------------
with tab[1]:
    st.header("Freshness Prediction")
    models_list = get_saved_models()
    selected_model = st.selectbox("Select a freshness model", models_list, key="select_freshness_model")
    
    if selected_model:
        freshness_model = create_cnn_model(num_classes=len(freshness_classes))
        freshness_model.load_weights(os.path.join(MODEL_DIR, selected_model))
        st.success(f"Loaded model: {selected_model}")

        uploaded_file = st.file_uploader("Upload image for freshness prediction", type=["jpg","jpeg","png"], key="upload_freshness_image")
        if uploaded_file:
            image = Image.open(uploaded_file).convert("RGB")
            st.image(image, caption="Uploaded Image", use_column_width=True)
            resized_img = image.resize((IMG_WIDTH, IMG_HEIGHT))
            input_array = np.expand_dims(np.array(resized_img)/255.0, axis=0)
            pred = freshness_model.predict(input_array)
            idx = np.argmax(pred, axis=1)[0]
            st.success(f"Prediction: {freshness_classes[idx]} ({pred[0][idx]:.2%})")
        
        if st.button("Delete selected model", key="delete_freshness"):
            os.remove(os.path.join(MODEL_DIR, selected_model))
            st.warning(f"Deleted model {selected_model}")

# -----------------------------
# INFERENCE: FRUIT TYPE
# -----------------------------
with tab[2]:
    st.header("Fruit Type Prediction")
    models_list = get_saved_models()
    selected_model = st.selectbox("Select a fruit type model", models_list, key="select_fruit_model")
    
    if selected_model:
        fruit_model = create_cnn_model(num_classes=len(fruit_classes))
        fruit_model.load_weights(os.path.join(MODEL_DIR, selected_model))
        st.success(f"Loaded model: {selected_model}")

        uploaded_file2 = st.file_uploader("Upload image for fruit prediction", type=["jpg","jpeg","png"], key="upload_fruit_image")
        if uploaded_file2:
            image = Image.open(uploaded_file2).convert("RGB")
            st.image(image, caption="Uploaded Image", use_column_width=True)
            resized_img = image.resize((IMG_WIDTH, IMG_HEIGHT))
            input_array = np.expand_dims(np.array(resized_img)/255.0, axis=0)
            pred = fruit_model.predict(input_array)
            idx = np.argmax(pred, axis=1)[0]
            st.success(f"Prediction: {fruit_classes[idx]} ({pred[0][idx]:.2%})")
        
        if st.button("Delete selected model", key="delete_fruit"):
            os.remove(os.path.join(MODEL_DIR, selected_model))
            st.warning(f"Deleted model {selected_model}")
